// Code generated by 'xmodel gen' command.
// DO NOT EDIT!

package args

import (
	"time"
)

// SQL CacheExpire
const CacheExpire = 24 * time.Hour

// UserSql the statement to create 'user' mysql table
const UserSql string = ``
